version: '3.8'
services: 
  api:
    container_name: 'api'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
    networks: 
      - local
    volumes:
      - .:/app
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_config:/data/configdb
    networks: 
      - local
networks:
  local:
    driver: bridge